from enum import StrEnum


class LifecycleStatus(StrEnum):
    UNRESOLVED = "UNRESOLVED"
    CANDIDATE = "CANDIDATE"
    WEIGHTED = "WEIGHTED"
    MEASURED = "MEASURED"
    COMMITTED = "COMMITTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class AttemptOutcome(StrEnum):
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"
    REPLAYED = "REPLAYED"


class Operation(StrEnum):
    TRANSITION = "TRANSITION"
    REOPEN = "REOPEN"


class CheckResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class FailureCategory(StrEnum):
    EVIDENTIARY = "EVIDENTIARY"
    PROCEDURAL = "PROCEDURAL"
    AUTHORITY = "AUTHORITY"
    INTEGRITY = "INTEGRITY"
    SUBSTANTIVE = "SUBSTANTIVE"


class ExpirySubject(StrEnum):
    CANDIDATE_ELIGIBILITY = "CANDIDATE_ELIGIBILITY"
    PRESENTATION_WINDOW = "PRESENTATION_WINDOW"
    OBSERVATION_WINDOW = "OBSERVATION_WINDOW"
    RULE_ELIGIBILITY = "RULE_ELIGIBILITY"
